apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-y0hq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-y0hq
    app.kubernetes.io/part-of: tkwch-fix-0075-0003-app
  name: devfile-sample-y0hq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-y0hq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-y0hq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0003-tenant/tkwch-fix-0075-0003-app/devfile-sample-y0hq@sha256:65e91c3f31b5215c575d96b45c026478047f8d4b6aa2154e4465430840a5daee
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
