apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-y0hq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0003-tenant/tkwch-fix-0075-0003-app/devfile-sample-y0hq@sha256:65e91c3f31b5215c575d96b45c026478047f8d4b6aa2154e4465430840a5daee
        name: my-nodejs
        resources: {}
status: {}
